// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
import 'dart:core';
import 'package:reflect_annotation_example/annotations.dart' as prefix2;
import 'package:reflect_annotation_example/form_reflector.dart' as prefix0;
import 'package:reflect_annotation_example/user_form.dart' as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.FormReflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'UserForm',
            r'.UserForm',
            134217735,
            0,
            const prefix0.FormReflector(),
            const <int>[0, 1, 6],
            const <int>[7, 8, 9, 10, 11, 2, 3, 4, 5],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => ({name, username}) =>
                  b ? prefix1.UserForm(name: name, username: username) : null
            },
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'name',
            67239941,
            0,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const <Object>[const prefix2.Required()]),
        r.VariableMirrorImpl(r'username', 67239941, 0,
            const prefix0.FormReflector(), -1, -1, -1, null, const <Object>[
          const prefix2.Required(),
          const prefix2.MaxLength(10)
        ]),
        r.ImplicitGetterMirrorImpl(const prefix0.FormReflector(), 0, 2),
        r.ImplicitSetterMirrorImpl(const prefix0.FormReflector(), 0, 3),
        r.ImplicitGetterMirrorImpl(const prefix0.FormReflector(), 1, 4),
        r.ImplicitSetterMirrorImpl(const prefix0.FormReflector(), 1, 5),
        r.MethodMirrorImpl(r'', 0, 0, -1, -1, -1, null, const <int>[0, 1],
            const prefix0.FormReflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[4],
            const prefix0.FormReflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.FormReflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[5], const prefix0.FormReflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.FormReflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.FormReflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'name',
            67253254,
            6,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #name),
        r.ParameterMirrorImpl(
            r'username',
            67253254,
            6,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            #username),
        r.ParameterMirrorImpl(
            r'_name',
            67240038,
            3,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_username',
            67240038,
            5,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            7,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            9,
            const prefix0.FormReflector(),
            -1,
            -1,
            -1,
            null,
            const [],
            null,
            null)
      ],
      <Type>[prefix1.UserForm],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'name': (dynamic instance) => instance.name,
        r'username': (dynamic instance) => instance.username
      },
      {
        r'name=': (dynamic instance, value) => instance.name = value,
        r'username=': (dynamic instance, value) => instance.username = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
